### ISSUE TITLE
sdk version

### ISSUE THREAD

**Issue by Bbalduzz** [Kirbyy1/RiotAuth#1]
yo, sick project, thx for mentioning my work :)
The only thing I would change is the Version() sdk method.

```
def sdk(self):
    return sdk if (sdk := requests.get("https://valorant-api.com/internal/ritoclientversion").json()["data"]["riotGamesApiInfo"]["VS_FIXEDFILEINFO"]["FileVersion"]) else "23.8.0.1382"
```

This provides a long-lasting support time :)

**Comment by Kirbyy1** [comment]
Hey,
I've applied the changes. Thank you very much.
